[package]
name = "w-ots"
version = "0.1.0"
authors = ["Vladislav Melnik <vladislav.melnik@protonmail.com>"]
edition = "2018"

[dependencies]
digest = { version = "0.8" }
hex = { version = "0.4" }
byteorder = { version = "1.3" }
